/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import direccion.Localidad;
import direccion.Provincia;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yohan
 */
public class FrmEmpleado extends java.awt.Dialog {
    public  static final String BTN_ADD="agregar";
    public  static final String BTN_EDIT="modificar";
    public  static final String BTN_DEL="borrar";
    public  static final String BTN_CANCEL="cancelar";
    public  static final String BTN_EXIT="salir";
    

    /**
     * Creates new form FrmEmpleado
     */
    public FrmEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        editar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnDel = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        txtTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        cmbLocalidad = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(240, 240, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, 686, 164));

        btnDel.setText("Eliminar");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 296, -1, -1));

        btnCancel.setText("Cancelar");
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 296, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 296, -1, -1));

        btnAdd.setText("Aceptar");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 296, -1, -1));

        btnEdit.setText("Modificar");
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 296, -1, -1));
        add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 171, 218, -1));

        jLabel10.setText("Numero:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 174, -1, -1));
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 129, 218, -1));

        jLabel12.setText("Cargo:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 216, -1, -1));

        jLabel6.setText("Telefono:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 168, -1, -1));

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 213, 176, -1));

        txtTel.setToolTipText("");
        add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 168, 218, -1));

        jLabel7.setText("Fecha de Nacimiento:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 206, -1, 24));

        jLabel8.setText("Provincia:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 48, -1, -1));

        jLabel9.setText("Localidad:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 90, -1, -1));

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 48, 176, -1));

        cmbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocalidadActionPerformed(evt);
            }
        });
        add(cmbLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 87, 176, -1));

        label1.setText("Legajo:");
        label1.setToolTipText("");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 48, -1, -1));

        txtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoActionPerformed(evt);
            }
        });
        add(txtLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 48, 218, -1));

        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 88, -1, -1));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 88, 218, -1));

        jLabel3.setText("DNI:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 128, -1, -1));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 128, 218, -1));

        jLabel4.setText("Fecha de Ingreso:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 248, -1, 24));

        jLabel5.setText("Calle:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 128, -1, 22));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 208, 216, -1));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 256, 213, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLocalidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEmpleado dialog = new FrmEmpleado(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JComboBox<String> cmbProvincia;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    
    void pasarControlador(ControladorEmpleado control) {
        btnAdd.setActionCommand(BTN_ADD);
        btnAdd.addActionListener(control);
        btnCancel.setActionCommand(BTN_CANCEL);
        btnCancel.addActionListener(control);
        btnDel.setActionCommand(BTN_DEL);
        btnDel.addActionListener(control);
        btnEdit.setActionCommand(BTN_EDIT);
        btnEdit.addActionListener(control);
        btnExit.setActionCommand(BTN_EXIT);
        btnExit.addActionListener(control);
        tabla.addMouseListener(control);
        cmbProvincia.addItemListener(control);
        
        
    }

    void limpiar() {
       txtCalle.setText("");
       txtDni.setText("");
       txtLegajo.setText("");
       txtNombre.setText("");
       txtNumero.setText("");
       txtTel.setText("");
    }

    void ponerCargos(ArrayList<Cargo> listaCargo) {
    cmbCargo.removeAllItems();
        for (Cargo c : listaCargo) {
            cmbCargo.addItem(c.getDescripcionCargo());
            
        }
    }

    void ponerProvincia(ArrayList<Provincia> lista) {
    cmbProvincia.removeAllItems();
        for (Provincia p : lista) {
            cmbProvincia.addItem(p.getNombreProv());
        }
    }

    public int getLegajo(){
        return Integer.parseInt(txtLegajo.getText());
        
    }

   public void setLegajo (int legajo){
       txtLegajo.setText(String.valueOf(legajo));
   }

   public String getNombre(){
       return txtNombre.getText();
   }

   public void setNombre(String nombre){
       txtNombre.setText(nombre);  
   }
   
   public String getDni(){
       return txtDni.getText();
   }
   
   public void setDni(String dni){
       txtDni.setText(dni);
   }
   
   public String getTelefono(){
       return txtTel.getText();
   }
   
   public void setTelefono(String telefono){
       txtTel.setText(telefono);
   }
   
   public java.util.Date getFechaNac(){
       return jDateChooser1.getDate();
   }
   
   public void setFechaNac(Date nac){
       jDateChooser1.setDate(nac);
   }
   
   public java.util.Date getFechaIng(){
       return jDateChooser2.getDate();
   }
   
   public void setFechaIng(Date ing){
       jDateChooser2.setDate(ing);  
   }
   
   public String getCargo(){
       return cmbCargo.getSelectedItem().toString();
   }
   
   public void setCargo(String cargo){
       cmbCargo.setSelectedItem(cargo);
   }
   
   public String getCalle(){
       return txtCalle.getText();
   }
   
   public void setCalle(String calle){
       txtCalle.setText(calle);
       
   }
   
   public int getNumero(){
       return Integer.parseInt(txtNumero.getText());
   }
   
   public void setNumero(int numero){
       txtNumero.setText(String.valueOf(numero));
   }
   
   public String getLocalidad(){
       return cmbLocalidad.getSelectedItem().toString();
   }
   public void setLocalidad(String localidad){
       cmbLocalidad.setSelectedItem(localidad);
   }
   
   public String getProvincia(){
       return cmbProvincia.getSelectedItem().toString();
   }
   
   public void setProvincia(String provincia){
       cmbProvincia.setSelectedItem(provincia);
   }

    void poneLocalidad(ArrayList<Localidad> lista) {
       cmbLocalidad.removeAllItems();
        for (Localidad l : lista) {
            cmbLocalidad.addItem(l.getNombreLoc());
        }
    }

    void editar(boolean b) {
        btnAdd.setEnabled(!b);
        btnDel.setEnabled(b);
        btnEdit.setEnabled(b);
    }

    

    void setTabla(DefaultTableModel matriz) {
        tabla.setModel(matriz);
    }
   
   
}
