/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import direccion.Localidad;
import direccion.Provincia;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yohan
 */
public class FrmCliente extends javax.swing.JDialog {

    public  static final String BTN_ADD="agregar";
    public  static final String BTN_EDIT="modificar";
    public  static final String BTN_DEL="borrar";
    public  static final String BTN_CANCEL="cancelar";
    public  static final String BTN_EXIT="salir";
    public  static final String BTN_CUENTA="cuenta";
    
    
    public FrmCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        editar(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        cmbLocalidad = new javax.swing.JComboBox<>();
        txtDni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnAdd = new javax.swing.JToggleButton();
        btnDel = new javax.swing.JToggleButton();
        btnEdit = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        btnCuenta = new javax.swing.JToggleButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Calle:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 111, -1, 22));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 151, 218, -1));

        jLabel10.setText("Número:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 154, -1, -1));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 111, 218, -1));

        jLabel8.setText("Provincia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 37, -1, -1));

        jLabel9.setText("Localidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 73, -1, -1));

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 34, 176, -1));

        cmbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 70, 176, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 34, 218, -1));

        jLabel11.setText("DNI:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 37, -1, -1));

        jLabel13.setText("Nombre y Apellido:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 73, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 70, 218, -1));

        jLabel14.setText("Teléfono:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 114, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 111, 218, -1));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, 734, 150));

        btnAdd.setText("Aceptar");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 204, -1, -1));

        btnDel.setText("Eliminar");
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 204, -1, -1));

        btnEdit.setText("Modificar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 204, -1, -1));

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 204, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 204, 71, -1));

        jLabel4.setText("Fecha de Alta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 151, -1, 24));

        btnCuenta.setText("Crear Cuenta");
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 204, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 151, 218, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCliente dialog = new FrmCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JToggleButton btnCuenta;
    private javax.swing.JToggleButton btnDel;
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JComboBox<String> cmbProvincia;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables


    void pasarControlador(ControladorCliente control) {
        btnAdd.setActionCommand(BTN_ADD);
        btnAdd.addActionListener(control);
        btnCancel.setActionCommand(BTN_CANCEL);
        btnCancel.addActionListener(control);
        btnDel.setActionCommand(BTN_DEL);
        btnDel.addActionListener(control);
        btnEdit.setActionCommand(BTN_EDIT);
        btnEdit.addActionListener(control);
        btnCuenta.setActionCommand(BTN_CUENTA);
        btnCuenta.addActionListener(control);
        btnExit.setActionCommand(BTN_EXIT);
        btnExit.addActionListener(control);
        tblCliente.addMouseListener(control);
        cmbProvincia.addItemListener(control);
        
        
    }
    
    void limpiar(){
        txtCalle.setText("");
        txtNumero.setText("");
        txtDni.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        
    }
    
    public String getDni(){
         return txtDni.getText();
    }

     public void setDni(String dni){
         txtDni.setText(dni);  
    }
    
    void ponerProvincia(ArrayList<Provincia> lista) {
    cmbProvincia.removeAllItems();
        for (Provincia p : lista) {
            cmbProvincia.addItem(p.getNombreProv());
        }
    }
    
    public String getProvincia(){
       return cmbProvincia.getSelectedItem().toString();
    }
   
    public void setProvincia(String provincia){
       cmbProvincia.setSelectedItem(provincia);
    }

    void poneLocalidad(ArrayList<Localidad> lista) {
       cmbLocalidad.removeAllItems();
        for (Localidad l : lista) {
            cmbLocalidad.addItem(l.getNombreLoc());
        }
    }
    
    public String getLocalidad(){
       return cmbLocalidad.getSelectedItem().toString();
    }
    
    public void setLocalidad(String localidad){
       cmbLocalidad.setSelectedItem(localidad);
    }
    
    public String getCalle(){
       return txtCalle.getText();
   }
   
   public void setCalle(String calle){
       txtCalle.setText(calle);
       
   }
   
   public int getNumero(){
       return Integer.parseInt(txtNumero.getText());
   }
   
   public void setNumero(int numero){
       this.txtNumero.setText(String.valueOf(numero));
   }
    
   public String getNombre(){
       return txtNombre.getText();
   }

   public void setNombre(String razon){
       txtNombre.setText(razon);  
   }
   
   public String getTelefono(){
       return txtTelefono.getText();
       
   }
   
   public void setTelefono(String telefono){
       txtTelefono.setText(telefono);
   }
   
   public java.util.Date getFechaAlta(){
        
       return jDateChooser1.getDate();
   }
   
   public void setFechaAlta(Date ing){
       jDateChooser1.setDate(ing);  
   }
   
   void editar(boolean b) {
        btnAdd.setEnabled(!b);
        btnDel.setEnabled(b);
        btnEdit.setEnabled(b);
    }

    

    void setTabla(DefaultTableModel matriz) {
        tblCliente.setModel(matriz);
    }

}
