/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regaleria;

/**
 *
 * @author YOHANA HERNANDEZ
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public static final String PROVINCIA="Provincia";
    public static final String LOCALIDAD="Localidad";
    public static final String CATEGORIA="Categoria";
    public static final String ARTICULO="Articulo";
    public static final String CARGO="Cargo";
    public static final String EMPLEADO="Empleado";
    public static final String CONCEPTO="Concepto";
    public static final String FAMILIAR="Familiar";
    public static final String PROVEEDOR="Proveedor";
    public static final String CLIENTE="Cliente";
    public static final String VENTA="Venta";
    public static final String PEDIDO="Pedido";
    public static final String LIQUIDACION="Liquidacion";
    public static final String MENU_SALIR="Menu_Salir";
    public static final String MENU_CERRAR_SESSION="cellar_sesion";
   
    
    public FrmMenu() {
        initComponents();
        
    }
    public void pasarControlador(Controlador control){
        menuProvincias.addActionListener(control);
        menuProvincias.setActionCommand(PROVINCIA);
        menuLocalidad.addActionListener(control);
        menuLocalidad.setActionCommand(LOCALIDAD);
        menuCategoria.addActionListener(control);
        menuCategoria.setActionCommand(CATEGORIA);
        menuArticulos.addActionListener(control);
        menuArticulos.setActionCommand(ARTICULO);
        menuVenta.setActionCommand(VENTA);
        menuCargo.addActionListener(control);
        menuCargo.setActionCommand(CARGO);
        menuEmpleados.setActionCommand(EMPLEADO);
        menuEmpleados.addActionListener(control);
        menuConcepto.setActionCommand(CONCEPTO);
        menuConcepto.addActionListener(control);
        menuFamilar.setActionCommand(FAMILIAR);
        menuFamilar.addActionListener(control);
        menuProveedor.setActionCommand(PROVEEDOR);
        menuProveedor.addActionListener(control);
        menuClientes.setActionCommand(CLIENTE);
        menuClientes.addActionListener(control);
        menuVenta.addActionListener(control);
        menuPedido.setActionCommand(PEDIDO);
        menuPedido.addActionListener(control);
        menuLiquidacion.addActionListener(control);
        menuLiquidacion.setActionCommand(LIQUIDACION);
        menuSalir.addActionListener(control);
        menuSalir.setActionCommand(MENU_SALIR);
        menuCerrarSesion.addActionListener(control);
        menuCerrarSesion.setActionCommand(MENU_CERRAR_SESSION);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpleado = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenuItem();
        menuAdm = new javax.swing.JMenu();
        menuArticulos = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenuItem();
        menuCargo = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuConcepto = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenuItem();
        menuFamilar = new javax.swing.JMenuItem();
        menuLiquidacion = new javax.swing.JMenuItem();
        menuLocalidad = new javax.swing.JMenuItem();
        menuProveedor = new javax.swing.JMenuItem();
        menuProvincias = new javax.swing.JMenuItem();
        menuRegaleria = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuEmpleado.setText("Empleado");

        menuPedido.setText("Pedido");
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        menuEmpleado.add(menuPedido);

        menuVenta.setText("Ventas");
        menuEmpleado.add(menuVenta);

        jMenuBar1.add(menuEmpleado);

        menuAdm.setText("Administrador");

        menuArticulos.setText("Artículo");
        menuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArticulosActionPerformed(evt);
            }
        });
        menuAdm.add(menuArticulos);

        menuCategoria.setText("Categoría del Artículo");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        menuAdm.add(menuCategoria);

        menuCargo.setText("Cargo del Empleado");
        menuAdm.add(menuCargo);

        menuClientes.setText("Cliente");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuAdm.add(menuClientes);

        menuConcepto.setText("Concepto");
        menuAdm.add(menuConcepto);

        menuEmpleados.setText("Empleado");
        menuAdm.add(menuEmpleados);

        menuFamilar.setText("Familiar del Empleado");
        menuAdm.add(menuFamilar);

        menuLiquidacion.setText("Liquidacion de haberes");
        menuAdm.add(menuLiquidacion);

        menuLocalidad.setText("Localidad");
        menuAdm.add(menuLocalidad);

        menuProveedor.setText("Proveedor");
        menuAdm.add(menuProveedor);

        menuProvincias.setText("Provincia");
        menuAdm.add(menuProvincias);

        jMenuBar1.add(menuAdm);

        menuRegaleria.setText("Regalería");

        menuSalir.setText("Salir");
        menuRegaleria.add(menuSalir);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuRegaleria.add(menuCerrarSesion);

        jMenuBar1.add(menuRegaleria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArticulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArticulosActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    

    public void menuAdm(){
        menuAdm.setVisible(true);
        menuEmpleado.setVisible(false);
        
    }
    public void menuEmpleado(){
        menuAdm.setVisible(false);
        menuEmpleado.setVisible(true);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdm;
    private javax.swing.JMenuItem menuArticulos;
    private javax.swing.JMenuItem menuCargo;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuConcepto;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenuItem menuEmpleados;
    private javax.swing.JMenuItem menuFamilar;
    private javax.swing.JMenuItem menuLiquidacion;
    private javax.swing.JMenuItem menuLocalidad;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuProvincias;
    private javax.swing.JMenu menuRegaleria;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVenta;
    // End of variables declaration//GEN-END:variables
}
